PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS commentaire (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  idKdo INTEGER NOT NULL DEFAULT 0,
  commentaire TEXT NOT NULL,
  creeLe TEXT NOT NULL DEFAULT '',
  creePar INTEGER NOT NULL DEFAULT 0,
  visible INTEGER NOT NULL DEFAULT 0,
  supprime INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS evenement (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  date TEXT NOT NULL DEFAULT '',
  titre TEXT NOT NULL DEFAULT '',
  description TEXT,
  groupe INTEGER NOT NULL DEFAULT 0,
  supprime INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS groupe (
  id INTEGER NOT NULL,
  idMembre INTEGER NOT NULL DEFAULT 0,
  nom TEXT DEFAULT NULL,
  PRIMARY KEY (id, idMembre)
);

CREATE TABLE IF NOT EXISTS kdo (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  pour INTEGER NOT NULL DEFAULT 0,
  titre TEXT NOT NULL DEFAULT '',
  description TEXT,
  url TEXT DEFAULT NULL,
  image TEXT DEFAULT NULL,
  creeLe TEXT NOT NULL DEFAULT '',
  creePar INTEGER NOT NULL DEFAULT 0,
  reserveLe TEXT DEFAULT NULL,
  reservePar INTEGER DEFAULT NULL,
  acheteLe TEXT DEFAULT NULL,
  achetePar INTEGER DEFAULT NULL,
  partage INTEGER NOT NULL DEFAULT 0,
  supprime INTEGER NOT NULL DEFAULT 0,
  priorite INTEGER NOT NULL DEFAULT 3
);

CREATE TABLE IF NOT EXISTS membre (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  motPasse TEXT NOT NULL DEFAULT '',
  prenom TEXT DEFAULT NULL,
  anniversaire TEXT DEFAULT NULL,
  presentation TEXT,
  email TEXT DEFAULT NULL,
  photo TEXT DEFAULT NULL,
  aime TEXT NOT NULL DEFAULT '',
  aimepas TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS partage (
  idKdo INTEGER DEFAULT 0,
  partagePar INTEGER NOT NULL DEFAULT 0,
  combien TEXT DEFAULT NULL,
  supprime INTEGER DEFAULT 0
);

INSERT INTO membre (prenom, motPasse, aime, aimepas)
SELECT 'vianney', 'ploki', '', ''
WHERE NOT EXISTS (
  SELECT 1 FROM membre WHERE prenom = 'vianney'
);
